image: python:latest
pages:
  stage: deploy
  only:
    - master
  script:
    - sudo apt-get install -f -y build-essential python3-dev python3-pip python3-setuptools python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
    - sudo apt-get install -f -y fonts-wqy-microhei chromium-driver
    - python3 -m pip install -U pip
    - python3 -m pip install -r requirements.txt
    - CI=1 ENABLE_PDF_EXPORT=1 python3 -m mkdocs build -d public
  artifacts:
    paths:
      - public
