site_name: name
# site_url:
site_description: description
site_author: author
# site_favicon: favicon
copyright: copyright (c)
# google_analytics:

repo_name: GitHub
repo_url: https://github.com/tqfx/mkdocs
remote_name: origin
remote_branch: gh-pages
edit_uri: edit/master/docs/

docs_dir: docs
site_dir: site
dev_addr: 127.0.0.1:8080

#https://facelessuser.github.io/pymdown-extensions/extensions
markdown_extensions:
  - toc:
      permalink: true
  #https://squidfunk.github.io/mkdocs-material/reference/abbreviations
  - abbr              # *[TEXT]: ...
  - pymdownx.snippets # --8<--
  #https://squidfunk.github.io/mkdocs-material/reference/admonitions
  - admonition            # !!! note "title"
  - pymdownx.details      # ??? note
  - pymdownx.superfences  # !!! note inline end
  #https://squidfunk.github.io/mkdocs-material/reference/buttons
  - attr_list # [text](#){ .md-button }
  #https://squidfunk.github.io/mkdocs-material/reference/code-blocks
  - pymdownx.inlinehilite # `#!c int`
  - pymdownx.highlight:   # ```
      linenums: false
      linenums_style: pymdownx.inline
  #https://squidfunk.github.io/mkdocs-material/reference/content-tabs
  - pymdownx.tabbed: # ===
      alternate_style: true
  #https://squidfunk.github.io/mkdocs-material/reference/data-tables
  - tables
  #https://squidfunk.github.io/mkdocs-material/reference/footnotes
  - footnotes # [^1]
  #https://squidfunk.github.io/mkdocs-material/reference/formatting
  - pymdownx.critic # {}
  - pymdownx.caret  # ^
  - pymdownx.keys   # +
  - pymdownx.mark   # =
  - pymdownx.tilde  # ~
  - pymdownx.betterem: # *
      smart_enable: all
  #https://squidfunk.github.io/mkdocs-material/reference/icons-emojis
  - pymdownx.emoji: # :smile:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  #https://squidfunk.github.io/mkdocs-material/reference/images
  - md_in_html
  #https://squidfunk.github.io/mkdocs-material/reference/lists
  - def_list # - [x]
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: false
  #https://squidfunk.github.io/mkdocs-material/reference/mathjax
  - pymdownx.arithmatex: # $$
      generic: true
  #https://squidfunk.github.io/mkdocs-material/reference/meta-tags
  - meta
  #https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions
  - pymdownx.smartsymbols # (c)

# theme_dir:
theme:
  name: material
  language: zh
  logo:
  favicon:
  icon: # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    repo: fontawesome/brands/github
  features:
    #https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigations
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    #https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search
    - search.suggest
    - search.highlight
    - search.share
    #https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#automatic-hiding
    - header.autohide
    #https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=annotate#code-annotations
    - content.code.annotate
  palette:
    #Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    #Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - git-revision-date: # https://github.com/zhaoterryy/mkdocs-git-revision-date-plugin
      enabled_if_env: CI # https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
  - with-pdf: # https://github.com/orzih/mkdocs-with-pdf
      # author: site_author
      # copyright: copyright
      #
      # cover: false # a cover page
      # back_cover: true # a back cover page
      # cover_title: site_name
      # cover_subtitle: None
      # cover_logo: None
      #
      toc_title: 目录
      # heading_shift: false
      # toc_level: 3
      # ordered_chapter_level: 2
      #
      render_js: true
      headless_chrome_path: chromium
      #
      output_path: index.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      #
      # debug_html: true
      # show_anchors: true
      # verbose: true

extra:
  #https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tqfx
  alternate: # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language
    #Switch to English
    - name: English
      link: /en/
      lang: en
  version: # https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning
    default: latest

extra_javascript:
  #mathjax
  #https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#arithmatex
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  #table
  #https://squidfunk.github.io/mkdocs-material/reference/data-tables/#sortable-tables
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/tablesort.js
