site_name: name
# site_url:
site_description: description
site_author: author
# site_favicon: favicon
copyright: copyright
# google_analytics:

repo_name: 'GitHub'
repo_url: https://github.com/tqfx/mkdocs/
remote_name: origin
remote_branch: gh-pages
edit_uri: 'edit/master/docs/'

docs_dir: docs
site_dir: site
dev_addr: '127.0.0.1:8080'

markdown_extensions:
  - meta
  - toc:
      permalink: true

  - abbr              # *[TEXT]: ...
  - pymdownx.snippets # --8<--

  - admonition            # !!! note "title"
  - pymdownx.details      # ??? note
  - pymdownx.superfences  # !!! note inline end

  - attr_list # [text](#){ .md-button }

  - pymdownx.inlinehilite # `#!c int`
  - pymdownx.highlight:   # ```
      linenums: false
      linenums_style: pymdownx.inline

  - pymdownx.tabbed # ===

  - footnotes # [^1]

  - pymdownx.critic # {}
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem:
      smart_enable: all 

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - def_list # - [x]
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: false

  - pymdownx.arithmatex: # $$
      generic: true

  - pymdownx.smartsymbols

# theme_dir:
theme:
  name: material
  custom_dir: overrides
  language: 'zh'
  highlightjs: true
  logo:
  favicon:
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - search.highlight
    - header.autohide
  palette:
    # Light mode
    - red: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - git-revision-date
  - with-pdf:
      #author: site_author
      #copyright: copyright
      #
      #cover: false
      #back_cover: true
      #cover_title: site_name
      cover_subtitle: subtitle
      #cover_logo: None
      #
      toc_title: 目录
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #
      #render_js: true
      #headless_chrome_path: chromedriver
      #
      output_path: index.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      #custom_template_path: TEMPLATES PATH
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tqfx/
  alternate:
    # Switch to English
    - name: English
      link: /en/
      lang: en
  version:
    default: latest

extra_css:
#- https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
  - css/default.css

extra_javascript:
# mathjax
#- https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/polyfill.js
#- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/tex-mml-chtml.js
# highlight
#- https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/highlight.js
# table
#- https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

